import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  // Seed settings
  await prisma.settings.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      waMessageTemplate:
        "Hi {{name}}, thanks for your interest in our services! I'd love to share more details and answer any questions you have. When would be a good time to chat?",
    },
  });

  // Get or create default org
  let org = await prisma.organization.findUnique({
    where: { slug: "demo-clinic" },
  });
  if (!org) {
    org = await prisma.organization.create({
      data: {
        name: "MedBeauty Clinic",
        slug: "demo-clinic",
      },
    });
  }

  const leads: Array<{
    metaLeadId: string;
    name: string;
    email?: string;
    phone?: string;
    campaignName: string;
    adsetName: string;
    adName: string;
    formName: string;
    status: "new" | "contacted" | "booked" | "closed" | "lost";
    bookingDate?: Date;
    saleAmount?: number;
    notes?: string;
    source: string;
    leadScore?: number;
    createdAt?: Date;
  }> = [
    // ── CLOSED (won) ────────────────────────────────────────────────
    {
      metaLeadId: "demo_001",
      name: "Ahmed Al-Rashid",
      email: "ahmed.rashid@gmail.com",
      phone: "971501234567",
      campaignName: "Spring Promo 2026",
      adsetName: "Men 30-50 UAE",
      adName: "Clinic Tour Video",
      formName: "Free Consultation",
      status: "closed",
      bookingDate: new Date("2026-03-10"),
      saleAmount: 4800,
      notes: "Rhinoplasty + chin augmentation. Very happy with result.",
      source: "webhook",
      leadScore: 94,
      createdAt: new Date("2026-02-20"),
    },
    {
      metaLeadId: "demo_002",
      name: "Isabella Rossi",
      email: "isabella.rossi@libero.it",
      phone: "393312345678",
      campaignName: "European Outreach",
      adsetName: "Italy Women 28-42",
      adName: "Before & After Carousel",
      formName: "Consultation Request",
      status: "closed",
      bookingDate: new Date("2026-03-05"),
      saleAmount: 3200,
      notes: "Lip augmentation and brow lift.",
      source: "webhook",
      leadScore: 88,
      createdAt: new Date("2026-02-14"),
    },
    {
      metaLeadId: "demo_003",
      name: "Nour Al-Farouk",
      email: "nour.farouk@outlook.com",
      phone: "201001234567",
      campaignName: "Gulf Campaign",
      adsetName: "Egypt Women 25-38",
      adName: "Doctor Testimonial",
      formName: "Free Consultation",
      status: "closed",
      bookingDate: new Date("2026-03-18"),
      saleAmount: 5500,
      notes: "Full face package. Referral from friend.",
      source: "webhook",
      leadScore: 91,
      createdAt: new Date("2026-02-28"),
    },
    {
      metaLeadId: "demo_004",
      name: "Lucas Fernández",
      email: "lucas.fdz@gmail.com",
      phone: "5491112345678",
      campaignName: "LATAM Campaign",
      adsetName: "Argentina Men 25-40",
      adName: "Results Showcase",
      formName: "Free Consultation",
      status: "closed",
      bookingDate: new Date("2026-03-22"),
      saleAmount: 2900,
      notes: "Hair transplant. Flew in from Buenos Aires.",
      source: "csv",
      leadScore: 82,
      createdAt: new Date("2026-03-01"),
    },
    // ── BOOKED ────────────────────────────────────────────────────────
    {
      metaLeadId: "demo_005",
      name: "Sarah Johnson",
      email: "sarah.johnson@email.com",
      phone: "15551234567",
      campaignName: "Spring Promo 2026",
      adsetName: "Women 25-40 USA",
      adName: "Before After Video",
      formName: "Consultation Request",
      status: "booked",
      bookingDate: new Date("2026-04-12"),
      notes: "Rhinoplasty consultation. Very motivated, asked about recovery time.",
      source: "webhook",
      leadScore: 87,
      createdAt: new Date("2026-03-15"),
    },
    {
      metaLeadId: "demo_006",
      name: "Hana Kovář",
      email: "hana.kovar@seznam.cz",
      phone: "420601234567",
      campaignName: "European Outreach",
      adsetName: "Czech Women 30-45",
      adName: "Clinic Photos",
      formName: "Consultation Request",
      status: "booked",
      bookingDate: new Date("2026-04-08"),
      notes: "Interested in eyelid surgery. Confirmed appointment.",
      source: "webhook",
      leadScore: 79,
      createdAt: new Date("2026-03-18"),
    },
    {
      metaLeadId: "demo_007",
      name: "Omar Khalid",
      email: "omar.khalid@hotmail.com",
      phone: "966551234567",
      campaignName: "Gulf Campaign",
      adsetName: "KSA Men 28-45",
      adName: "Hair Clinic Ad",
      formName: "Free Consultation",
      status: "booked",
      bookingDate: new Date("2026-04-15"),
      notes: "FUE hair transplant. Budget confirmed at $3k.",
      source: "webhook",
      leadScore: 85,
      createdAt: new Date("2026-03-20"),
    },
    {
      metaLeadId: "demo_008",
      name: "Chloe Dupont",
      email: "chloe.dupont@orange.fr",
      phone: "33612345678",
      campaignName: "European Outreach",
      adsetName: "France Women 22-35",
      adName: "Doctor Interview",
      formName: "Consultation Request",
      status: "booked",
      bookingDate: new Date("2026-04-20"),
      notes: "Rhinoplasty. Has referral discount code.",
      source: "webhook",
      leadScore: 76,
      createdAt: new Date("2026-03-22"),
    },
    // ── CONTACTED ─────────────────────────────────────────────────────
    {
      metaLeadId: "demo_009",
      name: "Maria González",
      email: "maria.g@hotmail.com",
      phone: "34612345678",
      campaignName: "European Outreach",
      adsetName: "Spain Women 20-35",
      adName: "Results Carousel",
      formName: "Consultation Request",
      status: "contacted",
      notes: "Asked about pricing. Needs follow-up this week.",
      source: "csv",
      leadScore: 62,
      createdAt: new Date("2026-03-10"),
    },
    {
      metaLeadId: "demo_010",
      name: "Yusuf Demir",
      email: "yusuf.demir@gmail.com",
      phone: "905321234567",
      campaignName: "Spring Promo 2026",
      adsetName: "Turkey Men 25-40",
      adName: "Transformation Story",
      formName: "Free Consultation",
      status: "contacted",
      notes: "Interested in jawline. WhatsApp replied, scheduling call.",
      source: "webhook",
      leadScore: 68,
      createdAt: new Date("2026-03-12"),
    },
    {
      metaLeadId: "demo_011",
      name: "Amira Hassan",
      email: "amira.hassan@yahoo.com",
      phone: "971551234567",
      campaignName: "Gulf Campaign",
      adsetName: "UAE Women 25-40",
      adName: "Testimonial Video",
      formName: "Consultation Request",
      status: "contacted",
      notes: "Wants nose job. Price-sensitive, offered payment plan.",
      source: "webhook",
      leadScore: 55,
      createdAt: new Date("2026-03-14"),
    },
    {
      metaLeadId: "demo_012",
      name: "Petra Novák",
      email: "petra.novak@gmail.com",
      phone: "420721234567",
      campaignName: "European Outreach",
      adsetName: "Czech Women 25-40",
      adName: "Clinic Tour",
      formName: "Free Consultation",
      status: "contacted",
      notes: "Liposuction inquiry. Sent brochure via email.",
      source: "webhook",
      leadScore: 58,
      createdAt: new Date("2026-03-16"),
    },
    {
      metaLeadId: "demo_013",
      name: "Carlos Mendoza",
      email: "carlos.m@gmail.com",
      phone: "5215512345678",
      campaignName: "LATAM Campaign",
      adsetName: "Mexico Men 30-45",
      adName: "Celebrity Feature",
      formName: "Consultation Request",
      status: "contacted",
      notes: "Hair implant. Comparing with local clinics.",
      source: "csv",
      leadScore: 51,
      createdAt: new Date("2026-03-17"),
    },
    {
      metaLeadId: "demo_014",
      name: "Layla Al-Mansouri",
      email: "layla.mansouri@outlook.com",
      phone: "97333123456",
      campaignName: "Gulf Campaign",
      adsetName: "Bahrain Women 22-38",
      adName: "Before After Video",
      formName: "Free Consultation",
      status: "contacted",
      notes: "Eye surgery. Wants virtual consultation first.",
      source: "webhook",
      leadScore: 64,
      createdAt: new Date("2026-03-19"),
    },
    // ── NEW ───────────────────────────────────────────────────────────
    {
      metaLeadId: "demo_015",
      name: "Lena Müller",
      email: "lena.muller@web.de",
      phone: "4915212345678",
      campaignName: "European Outreach",
      adsetName: "Germany Women 25-45",
      adName: "Doctor Interview",
      formName: "Free Consultation",
      status: "new",
      source: "webhook",
      leadScore: 71,
      createdAt: new Date("2026-03-25"),
    },
    {
      metaLeadId: "demo_016",
      name: "Fatima Al-Zahra",
      email: "fatima.alzahra@outlook.com",
      phone: "966501234567",
      campaignName: "Gulf Campaign",
      adsetName: "KSA Women 25-40",
      adName: "Testimonial Video",
      formName: "Consultation Request",
      status: "new",
      source: "webhook",
      leadScore: 66,
      createdAt: new Date("2026-03-26"),
    },
    {
      metaLeadId: "demo_017",
      name: "Sofia Papadopoulos",
      email: "sofia.papa@gmail.com",
      phone: "306912345678",
      campaignName: "European Outreach",
      adsetName: "Greece Women 23-38",
      adName: "Results Carousel",
      formName: "Consultation Request",
      status: "new",
      source: "webhook",
      leadScore: 73,
      createdAt: new Date("2026-03-27"),
    },
    {
      metaLeadId: "demo_018",
      name: "Khalid Al-Otaibi",
      email: "khalid.otaibi@gmail.com",
      phone: "966531234567",
      campaignName: "Gulf Campaign",
      adsetName: "KSA Men 25-40",
      adName: "Hair Clinic Ad",
      formName: "Free Consultation",
      status: "new",
      source: "webhook",
      leadScore: 59,
      createdAt: new Date("2026-03-28"),
    },
    {
      metaLeadId: "demo_019",
      name: "Elena Popescu",
      email: "elena.popescu@yahoo.ro",
      phone: "40721234567",
      campaignName: "European Outreach",
      adsetName: "Romania Women 25-40",
      adName: "Clinic Photos",
      formName: "Consultation Request",
      status: "new",
      source: "webhook",
      leadScore: 48,
      createdAt: new Date("2026-03-29"),
    },
    {
      metaLeadId: "demo_020",
      name: "Tarek Ibrahim",
      email: "tarek.ibrahim@gmail.com",
      phone: "201211234567",
      campaignName: "Gulf Campaign",
      adsetName: "Egypt Men 28-42",
      adName: "Doctor Testimonial",
      formName: "Free Consultation",
      status: "new",
      source: "webhook",
      leadScore: 77,
      createdAt: new Date("2026-03-30"),
    },
    {
      metaLeadId: "demo_021",
      name: "Andreea Constantin",
      email: "andreea.c@gmail.com",
      phone: "40741234567",
      campaignName: "European Outreach",
      adsetName: "Romania Women 22-35",
      adName: "Before After Video",
      formName: "Consultation Request",
      status: "new",
      source: "webhook",
      leadScore: 53,
      createdAt: new Date("2026-03-31"),
    },
    {
      metaLeadId: "demo_022",
      name: "Rania Aziz",
      email: "rania.aziz@hotmail.com",
      phone: "96171234567",
      campaignName: "Gulf Campaign",
      adsetName: "Lebanon Women 24-38",
      adName: "Transformation Story",
      formName: "Consultation Request",
      status: "new",
      source: "webhook",
      leadScore: 69,
      createdAt: new Date("2026-04-01"),
    },
    // ── LOST ─────────────────────────────────────────────────────────
    {
      metaLeadId: "demo_023",
      name: "James Wilson",
      email: "jwilson@gmail.com",
      phone: "447912345678",
      campaignName: "UK Campaign",
      adsetName: "UK Mixed 28-45",
      adName: "Celebrity Feature",
      formName: "Free Consultation",
      status: "lost",
      notes: "Not responding to messages. 3 follow-ups sent.",
      source: "csv",
      leadScore: 22,
      createdAt: new Date("2026-02-10"),
    },
    {
      metaLeadId: "demo_024",
      name: "Bogdan Ionescu",
      email: "bogdan.ionescu@gmail.com",
      phone: "40761234567",
      campaignName: "European Outreach",
      adsetName: "Romania Men 30-45",
      adName: "Clinic Tour",
      formName: "Free Consultation",
      status: "lost",
      notes: "Chose local provider. Too far to travel.",
      source: "webhook",
      leadScore: 18,
      createdAt: new Date("2026-02-15"),
    },
    {
      metaLeadId: "demo_025",
      name: "Ana Lima",
      email: "ana.lima@gmail.com",
      phone: "5511912345678",
      campaignName: "LATAM Campaign",
      adsetName: "Brazil Women 25-40",
      adName: "Results Showcase",
      formName: "Consultation Request",
      status: "lost",
      notes: "Budget too low for desired procedure.",
      source: "webhook",
      leadScore: 15,
      createdAt: new Date("2026-02-20"),
    },
  ];

  for (const { createdAt, ...lead } of leads) {
    await prisma.lead.upsert({
      where: { metaLeadId: lead.metaLeadId },
      update: {},
      create: {
        ...lead,
        orgId: org.id,
        createdAt: createdAt ?? new Date(),
      },
    });
  }

  console.log(`✅ Seeded ${leads.length} leads for "${org.name}"`);
  console.log("   Run: npm run dev — then visit http://localhost:3000");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
